version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      API_URL: http://localhost:8000/openapi.json